### ISSUE TITLE
License

### ISSUE THREAD

**Issue by artem-sidorenko** [asklv/SettingsSplitViewController#1]
@asklv thanks for a great example!

As this code is partly a bit more than a simple example and it might be reused on the generic way, it would be great if you could include some appropriate opensource license in this repository

**Comment by asklv** [comment]
I really think that this is the simple example. This project should not be used on the generic way, because it doesn't support long strings. And also I would place each controller in the separate storyboard. This is the simple example how iOS developer can resolve the task.
